# Generated by Django 5.2.6 on 2025-10-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
