# Generated by Django 5.2.6 on 2025-10-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tasks', '0002_priority_order_status_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Date_of_Adoption',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_Date_actual',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_Date_plan',
            field=models.DateTimeField(),
        ),
    ]
