# Generated by Django 5.2.6 on 2025-10-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tasks', '0003_alter_task_date_of_adoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Date_of_Adoption',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_Date_actual',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_Date_plan',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
