# Generated by Django 5.2.6 on 2025-10-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tasks', '0004_alter_task_date_of_adoption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Date_of_Adoption',
            new_name='date_of_Adoption',
        ),
    ]
